services:

  db:
    image: mysql:8.0
    container_name: mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: core
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: django_app_dev
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    volumes:
      - .:/app
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env.dev
    depends_on:
      - db
    entrypoint: ['./entrypoint.sh']

volumes:
  mysql_data:
